### ISSUE TITLE
The weird 'Full Stop'

### ISSUE THREAD

**Issue by Aspireve** [hrutik7/resume-builder#3]
The present website has a Full Stop located on the next line which makes it look a bit off.
Seeing the website and how well its build it would be great if the full stop can be placed on the upper line.

![image](https://user-images.githubusercontent.com/93852415/179677219-1f71fb73-8462-4548-8b9d-6b26b739faed.png)

**Comment by hrutik7** [comment]
Yes , that will looks good

**Comment by Aspireve** [comment]
Hey @hrutik7 Can I work on this?

**Comment by hrutik7** [comment]
That would be really gr8

**Comment by Aspireve** [comment]
Hey @hrutik7 I made the pull request, do review it and let me know if anything more is need.
